models/topic.py
import time

from sqlalchemy import String, Integer, Column, Text, UnicodeText, Unicode

from models.base_model import SQLMixin, db
from models.user import User
from models.reply import Reply


class Topic(SQLMixin, db.Model):
    views = Column(Integer, nullable=False, default=0)
    reply_counts = Column(Integer, nullable=False, default=0)
    title = Column(Unicode(50), nullable=False)
    content = Column(UnicodeText, nullable=False)
    user_id = Column(Integer, nullable=False)
    board_id = Column(Integer, nullable=False)

    @classmethod
    def new(cls, form, user_id):
        form['user_id'] = user_id
        m = super().new(form)
        return m

    @classmethod
    def get(cls, id):
        m = cls.one(id=id)
        m.views += 1
        m.save()
        return m

    def user(self):
        u = User.one(id=self.user_id)
        return u

    def replies(self):
        ms = Reply.all(topic_id=self.id)
        return ms

    def reply_count(self):
        count = len(self.replies())
        return count

routes/index.py
import os
import uuid
import json
import redis

from flask import (
    render_template,
    request,
    redirect,
    session,
    url_for,
    Blueprint,
    send_from_directory,
)
from werkzeug.datastructures import FileStorage
# from werkzeug.utils import secure_filename

from models.reply import Reply
from models.topic import Topic
from models.user import User
from routes import (
    current_user,
    topic_time_sorted,
    reply_time_sorted,
    new_csrf_token,
    csrf_required,
    login_required,
)

cache = redis.StrictRedis()
main = Blueprint('index', __name__)


@main.route("/")
def index():
    u = current_user()
    return render_template("index.html", user=u)


@main.route("/register", methods=['POST'])
def register():
    form = request.form.to_dict()
    User.register(form)
    return redirect(url_for('.index'))


@main.route("/register/view")
def register_view():
    return render_template("user/register.html")


@main.route("/login", methods=['POST'])
def login():
    form = request.form
    u = User.validate_login(form)
    if u is None:
        return redirect(url_for('.index'))
    else:
        # session 中写入 user_id
        session['user_id'] = u.id
        session.permanent = True
        return redirect(url_for('topic.index'))


@main.route("/logout")
def logout():
    session.pop('user_id')
    return redirect(url_for('index.index'))


def created_topic(user_id):
    k = 'created_topic_{}'.format(user_id)
    if cache.exists(k):
        v = cache.get(k)
        ts = json.loads(v)
        return ts
    else:
        ts = Topic.all(user_id=user_id)
        v = json.dumps([t.json() for t in ts])
        cache.set(k, v)
        return ts


def replied_topic(user_id):
    k = 'replied_topic_{}'.format(user_id)
    if cache.exists(k):
        v = cache.get(k)
        ts = json.loads(v)
        return ts
    else:
        rs = Reply.all(user_id=user_id)
        ts = []
        for r in rs:
            t = Topic.one(id=r.topic_id)
            ts.append(t)

        v = json.dumps([t.json() for t in ts if t is not None])
        cache.set(k, v)

        return ts


@main.route('/profile')
@login_required
def profile():
    u = current_user()
    return render_template(
        'user/profile.html',
        user=u,
    )


@main.route('/user/<int:id>')
@login_required
def user_detail(id):
    # TODO 需要修改
    u = User.one(id=id)
    topics = created_topic(u.id)
    topics = topic_time_sorted(topics)
    print('测试', topics)
    # topics = Topic.all(user_id=u.id)
    # topics = time_sorted(topics)
    reply = Reply.all(user_id=u.id)
    reply = reply_time_sorted(reply)
    return render_template('user/profile.html', user=u, topics=topics, reply=reply)


@main.route('/setting')
@login_required
def setting():
    token = new_csrf_token()
    u = current_user()
    if u is None:
        return redirect(url_for('index.index'))
    else:
        return render_template(
            'user/setting.html',
            user=u,
            token=token,
        )


@main.route('/info/update', methods=['POST'])
@csrf_required
def info_update():
    form = request.form.to_dict()
    u = current_user()
    User.update(u.id, **form)
    return redirect(url_for('index.setting'))


@main.route('/password/update', methods=['POST'])
@csrf_required
def password_update():
    form = request.form.to_dict()
    old_pass = form['old_pass']
    new_pass = User.salted_password(form['new_pass'])
    u = current_user()
    query = dict(
        username=u.username,
        password=old_pass,
    )
    if bool(User.validate_login(query)) is True:
        User.update(u.id, password=new_pass)
        return redirect(url_for('index.setting'))
    else:
        return redirect(url_for('index.index'))


@main.route('/image/add', methods=['POST'])
def avatar_add():
    file: FileStorage = request.files['avatar']
    # file = request.files['avatar']
    # filename = file.filename
    # ../../root/.ssh/authorized_keys
    # images/../../root/.ssh/authorized_keys
    # filename = secure_filename(file.filename)
    suffix = file.filename.split('.')[-1]
    filename = '{}.{}'.format(str(uuid.uuid4()), suffix)
    path = os.path.join('images', filename)
    file.save(path)

    u = current_user()
    User.update(u.id, image='/images/{}'.format(filename))
    return redirect(url_for('index.setting'))


@main.route('/images/<filename>')
def image(filename):
    # 直接拼接路由不安全，比如
    # http://localhost:2000/images/..%5Capp.py
    # path = os.path.join('images', filename)
    # print('images path', path)
    # return open(path, 'rb').read()
    # if filename in os.listdir('images'):
    #     return
    return send_from_directory('images', filename)

routes/reply.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
)

from models.message import Messages
from routes import *

from models.reply import Reply


main = Blueprint('reply', __name__)


def users_from_content(content):
    # 内容：@123 内容
    parts = content.split()
    users = []

    for p in parts:
        if p.startswith('@'):
            # @ 之后的用户名
            username = p[1:]
            u = User.one(username=username)
            print('users_from_content <{}> <{}> <{}>'.format(username, p, parts))
            if u is not None:
                users.append(u)

    return users


def send_mails(sender, receivers, reply_link, reply_content):
    print('send_mail', sender, receivers, reply_content)
    content = '链接：{}\n内容：{}'.format(
        reply_link,
        reply_content
    )
    for r in receivers:
        form = dict(
            title='你被 {} @ 了'.format(sender.username),
            content=content,
            sender_id=sender.id,
            receiver_id=r.id
        )
        Messages.new(form)


@main.route("/add", methods=["POST"])
def add():
    form = request.form
    u = current_user()

    content = form['content']
    users = users_from_content(content)
    # request.referrer 告诉服务器从哪个页面链接过来的
    send_mails(u, users, request.referrer, content)

    form = form.to_dict()
    m = Reply.new(form, user_id=u.id)
    return redirect(url_for('topic.detail', id=m.topic_id))

routes/topic.py
# import redis
# import json
from flask import (
    render_template,
    # redirect,
    # url_for,
    Blueprint,
)

from routes import *

from models.topic import Topic
from models.board import Board

main = Blueprint('topic', __name__)
# cache = redis.StrictRedis()


@main.route("/")
@login_required
def index():
    u = current_user()
    board_id = int(request.args.get('board_id', -1))
    if board_id == -1:
        ms = Topic.all()
    else:
        ms = Topic.all(board_id=board_id)
    token = new_csrf_token()
    bs = Board.all()
    return render_template("topic/index.html", ms=ms, token=token, bs=bs, bid=board_id, user=u)


# def cache_topic(topic_id):
#     k = 'cache_topic_{}'.format(topic_id)
#     if cache.exists(k):
#         v = cache.get(k)
#         topic = json.loads(v)
#         print('测试', type(topic), topic)
#         return topic
#     else:
#         topic = Topic.get(topic_id)
#         v = json.dumps(topic.json())
#         cache.set(k, v)
#         return topic


@main.route('/<int:id>')
def detail(id):
    u = current_user()
    m = Topic.get(id)
    board = Board.one(id=m.board_id)
    # 传递 topic 的所有 reply 到 页面中
    return render_template("topic/detail.html", topic=m, user=u, board=board)


@main.route("/delete")
@csrf_required
def delete():
    id = int(request.args.get('id'))
    Topic.delete(id)
    return redirect(url_for('.index'))


@main.route("/new")
def new():
    board_id = int(request.args.get('board_id'))
    bs = Board.all()
    token = new_csrf_token()
    return render_template("topic/new.html", bs=bs, token=token, bid=board_id)


@main.route("/add", methods=["POST"])
@csrf_required
def add():
    form = request.form.to_dict()
    u = current_user()
    Topic.new(form, user_id=u.id)
    return redirect(url_for('.index'))

templates/topic/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <link href="//cdn.bootcss.com/prism/1.8.0/themes/prism.css" rel="stylesheet">
    {% block css_js %}{% endblock %}
<head>
<body>

<!-- navbar -->
<div class='navbar'>
  <div class='navbar-inner'>
    <div class='container'>
        <a class="brand" href="{{ url_for('topic.index') }}">
          <img src="/images/0.png">
        </a>
      <ul class='nav pull-right'>
          <li><a href='{{ url_for('topic.index') }}'>首页</a></li>
{#          <li><a href='{{ url_for('index.register_view') }}'>注册</a></li>#}
{#          <li><a href='{{ url_for('index.index') }}'>登录</a></li>#}
          {% block navbar %}{% endblock %}
{#          <li><a href='/logout'>退出</a></li>#}
      </ul>
      <a class="btn btn-navbar" id="responsive-sidebar-trigger">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
    </div>
  </div>
</div>

{% block main %}
{% endblock %}
<footer class="footer navbar-fixed-bottom ">
    <div class="container">
        <p class="dark" style="text-align: right">备案：豫ICP备19019371号-1</p>
    </div>
</footer>
</body>

templates/topic/detail.html
{% extends "topic/base.html" %}
{% block title %}{{ topic.title }}{% endblock%}
{% block navbar %}
    <li><a href='/mail'>信息</a></li>
    <li><a href='/setting'>设置</a></li>
    <li><a href='/logout'>退出</a></li>
{% endblock %}
{% block main %}
<div id="main">
    <div id="sidebar">
        <div class="panel">
            <div class="header">
                <span class="col_fade">个人信息</span>
            </div>
            <div class="inner">
                <div class="user_card">
                    <div>
                        <a class="user_avatar" href="{{ url_for('index.user_detail', id=user.id) }}">
                            <img src="{{ user.image }}" title="{{ user.username }}">
                        </a>
                        <span class="user_name">
                            <a class="dark" href="{{ url_for('index.user_detail', id=user.id) }}">
                                {{ user.username }}
                            </a>
                        </span>
                        <div class="space clearfix"></div>
                        <span class="signature">
                            “ {{ user.signature }} ”
                        </span>
                    </div>
                </div>
            </div>
        </div>
        <div class="panel">
            <div class="inner">
                <a href="/topic/new?board_id=1" class="create_topic_btn">
                    <span class="span-success">发布话题</span>
                </a>
            </div>
        </div>
    </div>
    <div id="content">
        <div class='panel'>
            <div class='header topic_header'>
                <span class="topic_full_title">
                    {{ topic.title }}
                </span>
                <div class="changes">
                    <span>
                        发布于 {{ topic.created_time | format_time }}
                    </span>
                    <span>
                        {% set u = topic.user() %}
                        作者
                        <a href="{{ url_for('index.user_detail', id=topic.user().id) }}">
                            {{ u.username }}
{#                            作者 {{ topic.user().username }}#}
                        </a>
                    </span>
                    <span>
                        {{ topic.views }} 次浏览
                    </span>
                    <span>
                        来自 {{ board.title }}
                    </span>
                </div>
            </div>

            <div class='inner topic'>
                <div class='topic_content'>
                    <div class="markdown-text">{{ topic.content}}</div>
                </div>
            </div>
        </div>
        <div class='panel'>
            <div class='header'>
                <span class='col_fade'>
                    <!-- 过滤器 -->
                    共 {{ topic.replies() | count }} 回复
                </span>
            </div>
            {% for r in topic.replies() %}
                {% set u = r.user() %}
                <div class='cell reply_area reply_item'>
                    <div class='author_content'>
                        <div class='user_info'>
                            <a class='dark reply_author'>
                                {{ u.username }}
                            </a>
                            <a class="reply_time">
                                {{ loop.index }}楼 / {{ loop.length }}楼
                                <span class="reply-created-time" id="{{ r.created_time }}">{{ r.created_time | format_time }}</span>
                            </a>
                        </div>
                        <div class='user_action'>
                        <span>
                            <i class="fa up_btn
                              fa-thumbs-o-up
                              invisible" title="喜欢"></i>
                            <span class="up-count">
                            </span>
                        </span>
                        </div>
                    </div>
                    <div class='reply_content from-leiwei1991'>
                        <div class="markdown-text">{{ r.content }}</div>

                    </div>
                </div>
            {% endfor %}
        </div>
        <div class='panel'>
            <div class='header'>
                <span class='col_fade'>
                    添加回复
                </span>
            </div>
            <div class="inner reply">
                <form id="reply_form" class="form-horizontal" action="{{ url_for('reply.add')}}" method="post">
                    <div class="markdown_editor in_editor">
                        <div class="markdown_in_editor">
                            <input type="hidden" name="topic_id" value="{{ topic.id }}">
                            <textarea class="editor" name="content"></textarea>
                            <div class="editor_buttons">
                                <input type="submit" class="span-primary submit_btn" data-loading-text="回复中.." value="回复">
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>


<link rel="stylesheet" href="/static/css/bootstrap.min.css">
<link rel="stylesheet" href="/static/css/style.css">
<script src="https://cdn.bootcss.com/marked/0.3.19/marked.min.js"></script>
<script src="https://cdn.bootcss.com/prism/1.13.0/prism.js"></script>
<script src="https://cdn.bootcss.com/prism/1.13.0/plugins/autoloader/prism-autoloader.min.js"></script>
<script>
    var e = function (sel) {
        return document.querySelector(sel)
    }

    var es = function (sel) {
        return document.querySelectorAll(sel)
    }

    var markContents = function () {
        // markdown -> html 的处理放在高亮前面
        // 因为高亮是针对 html 格式的
        // lang -> language 不需要转 prism 自动转了
        var contentDivs = es('.markdown-text')
        for (var i = 0; i < contentDivs.length; i++) {
            var contentDiv = contentDivs[i]
            console.log('pre marked', contentDiv.textContent)
            var content = marked(contentDiv.textContent)
            console.log('after marked', content)
            contentDiv.innerHTML = content
        }
    }

    var highlight = function() {
         // 自动加载对应的语言 不然要手动加入各个语言的 js
        Prism.plugins.autoloader.languages_path = 'https://cdn.bootcss.com/prism/1.13.0/components/'
    }

    var __main = function () {
        markContents()
        highlight()
    }

    __main()

</script>

{% endblock %}

templates/topic/index.html
{% extends "topic/base.html" %}
{% block title %}论坛主页{% endblock%}
{% block navbar %}
    <li><a href='/mail'>信息</a></li>
    <li><a href='/setting'>设置</a></li>
    <li><a href='/logout'>退出</a></li>
{% endblock %}
{% block main %}

<div id="main">
    <div id="sidebar">
        <div class="panel">
            <div class="header">
                <span class="col_fade">个人信息</span>
            </div>
            <div class="inner">
                <div class="user_card">
                    <div>
                        <a class="user_avatar" href="{{ url_for('index.user_detail', id=user.id) }}">
                            <img src="{{ user.image }}" title="{{ user.username }}">
                        </a>
                        <span class="user_name">
                            <a class="dark" href="{{ url_for('index.user_detail', id=user.id) }}">
                                {{ user.username }}
                            </a>
                        </span>
                        <div class="space clearfix"></div>
                        <span class="signature">
                            “ {{ user.signature }} ”
                        </span>
                    </div>
                </div>
            </div>
        </div>
        <div class="panel">
            <div class="inner">
                <a href="/topic/new?board_id={{ bid }}" class="create_topic_btn">
                    <span class="span-success">发布话题</span>
                </a>
            </div>
        </div>
    </div>
    <div id="content">
        <div class="panel">
            <div class="header">
                <a href="/topic"
                   class="topic-tab current-tab">
                    全部的帖子
                </a>

                {% for b in bs %}
                <a href="/topic?board_id={{ b.id }}"
                   class="topic-tab current-tab">
                    {{ b.title }}
                </a>
                {% endfor %}
            </div>
            <div class="inner post  ">
                <div class="topic_list">
                    {% for t in ms %}
                    <div class="cell">
                        <a class="user_avatar pull-left" href="{{ url_for('index.user_detail', id=user.id) }}">
                            <img src="{{ user.image }}" title="{{ user.username }}">
                        </a>
                        <span class="reply_count pull-left">
                            <span class="count_of_replies" title="回复数">
                                {{ t.replies() | count }}
                            </span>
                            <span class="count_seperator">/</span>
                            <span class="count_of_visits" title="点击数">
                                {{ t.views }}
                            </span>
                        </span>
                        <div class="topic_title_wrapper">
                            <span class="topiclist-tab">问答</span>
                            <a class="topic_title" href="{{ url_for('topic.detail', id=t.id) }}">
                                {{ t.title }}
                            </a>
{#                            <span>{{ t.replies() | count }} / {{ t.views }}</span>#}
                            <!--<a class="topic_title" href="{{ url_for('topic.delete', id=t.id) }}">-->
                            <a class="topic_title" href="{{ url_for('topic.delete', id=t.id, token=token) }}">
                                删除
                            </a>

                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
<script>
  (function () {
    var editor = new Editor();
    editor.render($('.editor')[0]);
  })();

</script>

{% endblock %}

templates/topic/new.html
{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <title>bbs club</title>#}
{#    <link rel="stylesheet" href="/static/css/bootstrap.min.css">#}
{#    <link rel="stylesheet" href="/static/css/style.css">#}
{#    <link rel="stylesheet" href="/static/lib/editor/editor.css">#}
{#    <link rel="stylesheet" href="/static/lib/webuploader/webuploader.css">#}
{#    <script src="/static/lib/jquery-3.0.0.min.js"></script>#}
{#    <script src="/static/lib/markdownit.js"></script>#}
{#    <script src="/static/lib/webuploader/webuploader.withoutimage.js"></script>#}
{#    <script src="/static/lib/editor/editor.js"></script>#}
{#    <script src="/static/lib/editor/ext.js"></script>#}
{#</head>#}
{#<body>#}
{% extends "topic/base.html" %}
{% block title %}论坛主页{% endblock%}
{% block css_js %}
    <link rel="stylesheet" href="/static/lib/editor/editor.css">
    <link rel="stylesheet" href="/static/lib/webuploader/webuploader.css">
    <script src="/static/lib/jquery-3.0.0.min.js"></script>
    <script src="/static/lib/markdownit.js"></script>
    <script src="/static/lib/webuploader/webuploader.withoutimage.js"></script>
    <script src="/static/lib/editor/editor.js"></script>
    <script src="/static/lib/editor/ext.js"></script>
{% endblock %}
{% block navbar %}
    <li><a href='/mail'>信息</a></li>
    <li><a href='/setting'>设置</a></li>
    <li><a href='/logout'>退出</a></li>
{% endblock %}
{% block main %}
    <div id="main">
        <div id="sidebar">
            <div class="panel">
                <div class="header">
                    <span class="col_fade">关于</span>
                </div>
                <div class="inner">
                    <div class="user_card">
                        这里什么也没有
                    </div>
                </div>
            </div>
        </div>
        <div id="content">
            <div class="panel">
                <div class="inner post">
<form id="create_topic_form" method="post" action="{{ url_for('.add', token=token) }}">
<!--<form id="create_topic_form" method="post" action="{{ url_for('.add') }}">-->
    <fieldset>
        <textarea autofocus class='span9' id='title'
                  name='title' rows='1'
                  placeholder="标题字数 10 字以上"></textarea>
        <span class="tab-selector">选择版块：</span>
        <select name="board_id" id="board" required>
            {% for b in bs %}
                {% if bid == b.id %}
                    <option value="{{ b.id }}" selected >{{ b.title }}</option>
                {% else %}
                    <option value="{{ b.id }}" >{{ b.title }}</option>
                {% endif %}
            {% endfor %}
        </select>
        <div class='markdown_editor in_editor'>
          <div class='markdown_in_editor'>
            <textarea class='editor' name='content' rows='20' placeholder='文章支持 Markdown 语法, 请注意标记代码'></textarea>
            <div class='editor_buttons'>
              <input type="submit" class='span-primary submit_btn' data-loading-text="提交中" value="提交">
            </div>
          </div>
        </div>
    </fieldset>
</form>
                </div>
            </div>
        </div>
    </div>
<script>
  (function () {
    var editor = new Editor();
    editor.render($('.editor')[0]);
  })();
</script>
{% endblock %}
{#</body>#}
{#</html>#}