models/user.py
import hashlib

from sqlalchemy import Column, String

import config
from models.base_model import SQLMixin, db


class User(SQLMixin, db.Model):
    __tablename__ = 'User'

    username = Column(String(50), nullable=False)
    password = Column(String(100), nullable=False)
    image = Column(String(100), nullable=False, default='/images/3.jpg')
    email = Column(String(50), nullable=False, default=config.test_mail)
    signature = Column(String(100), nullable=False, default='什么也没有留下')

    @staticmethod
    def salted_password(password, salt='$!@><?>HUI&DWQa`'):
        salted = hashlib.sha256((password + salt).encode('ascii')).hexdigest()
        return salted

    @classmethod
    def register(cls, form):
        name = form.get('username', '')
        if len(name) > 3 and User.one(username=name) is None:
            form['password'] = User.salted_password(form['password'])
            u = User.new(form)
            return u
        else:
            return None

    @classmethod
    def validate_login(cls, form):
        query = dict(
            username=form['username'],
            password=User.salted_password(form['password']),
        )
        return User.one(**query)

routes/index.py
import os
import uuid
import json
import redis

from flask import (
    render_template,
    request,
    redirect,
    session,
    url_for,
    Blueprint,
    send_from_directory,
)
from werkzeug.datastructures import FileStorage
# from werkzeug.utils import secure_filename

from models.reply import Reply
from models.topic import Topic
from models.user import User
from routes import (
    current_user,
    topic_time_sorted,
    reply_time_sorted,
    new_csrf_token,
    csrf_required,
    login_required,
)

cache = redis.StrictRedis()
main = Blueprint('index', __name__)


@main.route("/")
def index():
    u = current_user()
    return render_template("index.html", user=u)


@main.route("/register", methods=['POST'])
def register():
    form = request.form.to_dict()
    User.register(form)
    return redirect(url_for('.index'))


@main.route("/register/view")
def register_view():
    return render_template("user/register.html")


@main.route("/login", methods=['POST'])
def login():
    form = request.form
    u = User.validate_login(form)
    if u is None:
        return redirect(url_for('.index'))
    else:
        # session 中写入 user_id
        session['user_id'] = u.id
        session.permanent = True
        return redirect(url_for('topic.index'))


@main.route("/logout")
def logout():
    session.pop('user_id')
    return redirect(url_for('index.index'))


def created_topic(user_id):
    k = 'created_topic_{}'.format(user_id)
    if cache.exists(k):
        v = cache.get(k)
        ts = json.loads(v)
        return ts
    else:
        ts = Topic.all(user_id=user_id)
        v = json.dumps([t.json() for t in ts])
        cache.set(k, v)
        return ts


def replied_topic(user_id):
    k = 'replied_topic_{}'.format(user_id)
    if cache.exists(k):
        v = cache.get(k)
        ts = json.loads(v)
        return ts
    else:
        rs = Reply.all(user_id=user_id)
        ts = []
        for r in rs:
            t = Topic.one(id=r.topic_id)
            ts.append(t)

        v = json.dumps([t.json() for t in ts if t is not None])
        cache.set(k, v)

        return ts


@main.route('/profile')
@login_required
def profile():
    u = current_user()
    return render_template(
        'user/profile.html',
        user=u,
    )


@main.route('/user/<int:id>')
@login_required
def user_detail(id):
    # TODO 需要修改
    u = User.one(id=id)
    topics = created_topic(u.id)
    topics = topic_time_sorted(topics)
    print('测试', topics)
    # topics = Topic.all(user_id=u.id)
    # topics = time_sorted(topics)
    reply = Reply.all(user_id=u.id)
    reply = reply_time_sorted(reply)
    return render_template('user/profile.html', user=u, topics=topics, reply=reply)


@main.route('/setting')
@login_required
def setting():
    token = new_csrf_token()
    u = current_user()
    if u is None:
        return redirect(url_for('index.index'))
    else:
        return render_template(
            'user/setting.html',
            user=u,
            token=token,
        )


@main.route('/info/update', methods=['POST'])
@csrf_required
def info_update():
    form = request.form.to_dict()
    u = current_user()
    User.update(u.id, **form)
    return redirect(url_for('index.setting'))


@main.route('/password/update', methods=['POST'])
@csrf_required
def password_update():
    form = request.form.to_dict()
    old_pass = form['old_pass']
    new_pass = User.salted_password(form['new_pass'])
    u = current_user()
    query = dict(
        username=u.username,
        password=old_pass,
    )
    if bool(User.validate_login(query)) is True:
        User.update(u.id, password=new_pass)
        return redirect(url_for('index.setting'))
    else:
        return redirect(url_for('index.index'))


@main.route('/image/add', methods=['POST'])
def avatar_add():
    file: FileStorage = request.files['avatar']
    # file = request.files['avatar']
    # filename = file.filename
    # ../../root/.ssh/authorized_keys
    # images/../../root/.ssh/authorized_keys
    # filename = secure_filename(file.filename)
    suffix = file.filename.split('.')[-1]
    filename = '{}.{}'.format(str(uuid.uuid4()), suffix)
    path = os.path.join('images', filename)
    file.save(path)

    u = current_user()
    User.update(u.id, image='/images/{}'.format(filename))
    return redirect(url_for('index.setting'))


@main.route('/images/<filename>')
def image(filename):
    # 直接拼接路由不安全，比如
    # http://localhost:2000/images/..%5Capp.py
    # path = os.path.join('images', filename)
    # print('images path', path)
    # return open(path, 'rb').read()
    # if filename in os.listdir('images'):
    #     return
    return send_from_directory('images', filename)

routes/topic.py
# import redis
# import json
from flask import (
    render_template,
    # redirect,
    # url_for,
    Blueprint,
)

from routes import *

from models.topic import Topic
from models.board import Board

main = Blueprint('topic', __name__)
# cache = redis.StrictRedis()


@main.route("/")
@login_required
def index():
    u = current_user()
    board_id = int(request.args.get('board_id', -1))
    if board_id == -1:
        ms = Topic.all()
    else:
        ms = Topic.all(board_id=board_id)
    token = new_csrf_token()
    bs = Board.all()
    return render_template("topic/index.html", ms=ms, token=token, bs=bs, bid=board_id, user=u)


# def cache_topic(topic_id):
#     k = 'cache_topic_{}'.format(topic_id)
#     if cache.exists(k):
#         v = cache.get(k)
#         topic = json.loads(v)
#         print('测试', type(topic), topic)
#         return topic
#     else:
#         topic = Topic.get(topic_id)
#         v = json.dumps(topic.json())
#         cache.set(k, v)
#         return topic


@main.route('/<int:id>')
def detail(id):
    u = current_user()
    m = Topic.get(id)
    board = Board.one(id=m.board_id)
    # 传递 topic 的所有 reply 到 页面中
    return render_template("topic/detail.html", topic=m, user=u, board=board)


@main.route("/delete")
@csrf_required
def delete():
    id = int(request.args.get('id'))
    Topic.delete(id)
    return redirect(url_for('.index'))


@main.route("/new")
def new():
    board_id = int(request.args.get('board_id'))
    bs = Board.all()
    token = new_csrf_token()
    return render_template("topic/new.html", bs=bs, token=token, bid=board_id)


@main.route("/add", methods=["POST"])
@csrf_required
def add():
    form = request.form.to_dict()
    u = current_user()
    Topic.new(form, user_id=u.id)
    return redirect(url_for('.index'))

templates/user/profile.html
{% extends "topic/base.html" %}
{% block title %}profile{% endblock%}
{% block navbar %}
    <li><a href='/mail'>信息</a></li>
    <li><a href='/setting'>设置</a></li>
    <li><a href='/logout'>退出</a></li>
{% endblock %}
{% block main %}
    <div id="main">
        {#侧边栏#}
        <div id="sidebar">
            <div class="panel">
                <div class="header">
                    <span class="col_fade">个人信息</span>
                </div>
                <div class="inner">
                    <div class="user_card">
                        <div>
                            <a class="user_avatar" href="{{ url_for('index.user_detail', id=user.id) }}">
                                <img src="{{ user.image }}" title="{{ user.username }}">
                            </a>
                            <span class="user_name">
                                <a class="dark" href="{{ url_for('index.user_detail', id=user.id) }}">
                                    {{ user.username }}
                                </a>
                            </span>
                            <div class="space clearfix"></div>
                            <span class="signature">
                                " {{ user.signature }} "
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div id="content">
            {# 个人信息 #}
            <div class="panel">
                <div class="header">
                    <ul class="breadcrumb">
                        <li>
                            <a href="{{ url_for('topic.index') }}">主页</a>
                            <span class="divider">/</span>
                        </li>
                    </ul>
                </div>
                <div class="inner userinfo">
                    <div class="user_big_avatar">
                        <img src="{{ user.image }}" class="user_avatar" title="{{ user.username }}">
                    </div>
                    <a class="dark">{{ user.username }}</a>
                </div>
            </div>
            {#最近创建的话题#}
            <div class="panel">
                <div class="header">
                    <span class="col_fade">最近创建的话题</span>
                </div>
                {% for t in topics %}
                    <div class="cell">
                        {#用户#}
                        <a class="user_avatar pull-left" href="{{ url_for('index.user_detail', id=user.id) }}">
                            <img src="{{ user.image }}" title="{{ user.username }}">
                        </a>
                        {#回复统计#}
                        <span class="reply_count pull-left">
                            <span class="count_of_replies" title="回复数">
                                {{ t.reply_counts }}
                            </span>
                            <span class="count_seperator">/</span>
                            <span class="count_of_visits" title="点击数">
                                {{ t.views }}
                            </span>
                        </span>
                        {#回复的用户#}
                        <a class="last_time pull-right">
                            <img class="user_small_avatar" src="{{ user.image }}">
                            <span class="last_active_time" data-created_time="{{ t.created_time }}"></span>
                        </a>
                        {#话题#}
                        <div class="topic_title_wrapper">
                            <a class="topic_title" href="{{ url_for('topic.detail', id=t.id) }}" title="{{ t.title }}">
                                {{ t.title }}
                            </a>
                        </div>
                    </div>
                {% endfor %}
            </div>
            {#最近参与的话题#}
            <div class="panel">
                <div class="header">
                    <span class="col_fade">最近参与的话题</span>
                </div>
                {% for r in reply %}
                    <div class="cell">
                        {#用户#}
                        <a class="user_avatar pull-left" href="{{ url_for('index.user_detail', id=user.id) }}">
                            <img src="{{ user.image }}" title="{{ user.username }}">
                        </a>
                        {#回复统计#}
                        <span class="reply_count pull-left">
                            <span class="count_of_replies" title="回复数">
                                {% if r.topic() is none %}
                                    0
                                {% else %}
                                    {{ r.topic().reply_count() }}
                                {% endif %}
                            </span>
                            <span class="count_seperator">/</span>
                            <span class="count_of_visits" title="点击数">
                                {{ r.topic().views }}
                            </span>
                        </span>
                        {#回复的用户#}
                        <a class="last_time pull-right">
                            <img class="user_small_avatar" src="{{ user.image }}">
                            <span class="last_active_time" data-created_time="{{ r.created_time }}"></span>
                        </a>
                        {#话题#}
                        <div class="topic_title_wrapper">
                            <a class="topic_title" href="{{ url_for('topic.detail', id=r.topic_id) }}" title="{{ r.topic().title }}">
                                {{ r.topic().title }}
                            </a>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
<script>
    var es = function (sel) {
        return document.querySelectorAll(sel)
    }
    var registerTimer = function () {
        setInterval(function () {
            var times = es('.last_active_time')
            for (var i = 0; i < times.length; i++) {
                var t = times[i]
                // data-created_time --> dataset.created_time
                var time = Number(t.dataset.created_time)
                var now = Math.floor(new Date() / 1000)
                var delta = now - time
                if (delta >= 3600) {
                    delta = Math.floor(delta / 3600)
                    var hour = `${delta} 小时前`
                    t.innerText = hour
                } else if (delta >= 60) {
                    delta = Math.floor(delta / 60)
                    var minute = `${delta} 分钟前`
                    t.innerText = minute
                } else if (delta < 60) {
                    var second = `${delta} 秒前`
                    t.innerText = second
                }
            }
        }, 1000)
    }

    var __main = function () {
        registerTimer()
    }

    __main()
</script>

{% endblock %}

templates/user/register.html
{% extends "topic/base.html" %}
{% block title %}注册{% endblock%}
{% block navbar %}
    <li><a href='{{ url_for('index.register_view') }}'>注册</a></li>
    <li><a href='{{ url_for('index.index') }}'>登录</a></li>
{% endblock %}
{% block main %}
<div id="main">
{#    侧边栏#}
    <div id="sidebar">
        <div class="panel">
            <div class="header">
                <span class="col_fade">关于</span>
            </div>
            <div class="inner">
                <div class="user_card">
                    <p>个人学习使用，邮箱：928283663@qq.com</p>
                    <p>测试账号：test/123456</p>
                </div>
            </div>
        </div>
    </div>
    <div id="content">
        <div class="panel">
            <div class="header">
                <ul class="breadcrumb">
                    <li><a href="{{ url_for('topic.index') }}">主页</a><span class="divider">/</span></li>
                    <li class="active">注册</li>
                </ul>
            </div>
            <div class="inner">
                <form class="form-horizontal" method="post" action="{{ url_for('.register') }}">
                    <div class="control-group">
                        <label class="control-label">用户名</label>
                        <div class="controls">
                            <input type="text" class="input-xlarge" name="username" placeholder="请输入用户名" disabled="disabled">
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label">密码</label>
                        <div class="controls">
                            <input type="password" class="input-xlarge" name="password" placeholder="请输入密码" disabled="disabled">
                        </div>
                    </div>
                    <div class="form-actions">
                        <input type="submit" class="span-primary" value="注册">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/user/setting.html
{% extends "topic/base.html" %}
{% block title %}设置{% endblock%}
{% block navbar %}
    <li><a href='/mail'>信息</a></li>
    <li><a href='/logout'>退出</a></li>
{% endblock %}
{% block main %}

<div id="main">
{#    侧边栏#}
    <div id="sidebar">
        <div class="panel">
            <div class="header">
                <span class="col_fade">个人信息</span>
            </div>
            <div class="inner">
                <div class="user_card">
                    <div>
                        <a class="user_avatar" href="{{ url_for('index.user_detail', id=user.id) }}">
                            <img src="{{ user.image }}" title="{{ user.username }}">
                        </a>
                        <span class="user_name">
                            <a class="dark" href="{{ url_for('index.user_detail', id=user.id) }}">
                                {{ user.username }}
                            </a>
                        </span>
                        <div class="space clearfix"></div>
                        <span class="signature">
                            {{ user.signature }}
                        </span>
                    </div>
                </div>
            </div>
        </div>
        <div class="panel">
            <div class="inner">
                <a href="{{ url_for('topic.new') }}" class="create_topic_btn">
                    <span class="span-success">发布话题xxxxxxxxxxxxxxxx</span>
                </a>
            </div>
        </div>
    </div>
    <div id="content">
        <div class="panel">
            <div class="header">
                <ul class="breadcrumb">
                    <li><a href="{{ url_for('topic.index') }}">主页</a><span class="divider">/</span></li>
                    <li class="active">设置</li>
                </ul>
            </div>
            <div class="inner">
                <form id="setting_form" class="form-horizontal" action="{{ url_for('index.info_update', token=token)}}" method="post">
                    <div class="control-group">
                        <label class="control-label" for="name">用户名</label>
                        <div class="controls">
                            <input class="input-xlarge readonly" id="name" name="name" size="30" type="text"
                                   readonly="true" value="{{ user.username }}">
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label" for="signature">个性签名</label>
                        <div class="controls">
                            <textarea class="input-xlarge" id="signature" name="signature" size="30">{{ user.signature }}</textarea>
                        </div>
                    </div>
                    <div class="form-actions">
                        <input type="submit" class="span-primary submit_btn" data-loading-text="保存中.." value="保存设置">
                    </div>
                </form>
            </div>
        </div>
        <div class="panel">
            <div class="header">
                <span class="col_fade">更改密码</span>
            </div>
            <div class="inner">
                <form id="change_pass_form" class="form-horizontal" action="{{ url_for('index.password_update', token=token)}}" method="post">
                    <div class="control-group">
                        <label class="control-label" for="old_pass">当前密码</label>
                        <div class="controls">
                            <input class="input-xlarge" type="password" id="old_pass" name="old_pass" size="30">
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label" for="new_pass">新密码</label>
                        <div class="controls">
                            <input class="input-xlarge" type="password" id="new_pass" name="new_pass" size="30">
                        </div>
                    </div>
                    <div class="form-actions">
                        <input type="submit" class="span-primary submit_btn" data-loading-text="更改中.." value="更改密码">
                    </div>
                </form>
            </div>
        </div>
        <div class="panel">
            <div class="header">
                <span class="col_fade">上传头像</span>
            </div>
            <div class="inner">
                <form id="change_pass_form" class="form-horizontal" action="{{ url_for('.avatar_add',token=token)}}" method="post" enctype="multipart/form-data">
                    <div class="control-group">
                        <div class="controls">
                            <input class="input-xlarge" type="file" id="new_pass" name="avatar" size="30">
                            <input type="submit" class="span-primary submit_btn" data-loading-text="更改中.." value="上传头像">
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}